services:
  metabase:
    build:
      context: ../metabase
    image: metabase-clickhouse:latest
    container_name: metabase
    ports:
      - "${METABASE_PORT}:3000"
    volumes:
      - ../storage/metabase:/metabase.db
    networks:
      - network

networks:
  network:
    driver: bridge
    name: network
