services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.9
    container_name: dw-clickhouse
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: ${CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT}
      CLICKHOUSE_TCP_PORT: ${CLICKHOUSE_TCP_PORT}
      CLICKHOUSE_HTTP_PORT: ${CLICKHOUSE_HTTP_PORT}
    ports:
      - ${CLICKHOUSE_HTTP_PORT}:${CLICKHOUSE_HTTP_PORT} # For Clickhouse Web UI
    expose:
      - ${CLICKHOUSE_TCP_PORT}
    volumes:
      - ../storage/clickhouse:/var/lib/clickhouse
      - ../storage/clickhouse-logs:/var/log/clickhouse-server/
      - ../clickhouse/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ../clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - network

networks:
  network:
    driver: bridge
    name: network
