name: Code Quality Checks

on:
  pull_request:
    branches: [main, develop, staging]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort codespell

      - name: Run flake8
        run: |
          flake8 --max-line-length 88 --extend-ignore E203,E701

      - name: Run isort
        run: |
          isort --profile black --src pipeline --check-only .

      - name: Run codespell
        run: |
          codespell
